# Generated by Django 2.2.10 on 2021-07-01 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='City_mst',
            fields=[
                ('city_code', models.TextField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('city_name', models.TextField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'city_mst',
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('m_code', models.TextField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('m_desc', models.TextField(blank=True, max_length=150, null=True)),
                ('s_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modules_mst',
            },
        ),
        migrations.CreateModel(
            name='UserWithcity',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.TextField(blank=True, max_length=10)),
                ('city_name', models.TextField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'userwithcity',
                'unique_together': {('user_id', 'city_name')},
            },
        ),
        migrations.CreateModel(
            name='Modules_indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField(blank=True, null=True)),
                ('sub_theme', models.TextField(blank=True, max_length=150, null=True)),
                ('indicator', models.TextField(blank=True, max_length=150, null=True)),
                ('formula', models.TextField(blank=True, max_length=150, null=True)),
                ('unit', models.TextField(blank=True, max_length=150, null=True)),
                ('benchmark', models.TextField(blank=True, max_length=150, null=True)),
                ('source_of_benchmark', models.TextField(blank=True, max_length=150, null=True)),
                ('category', models.TextField(blank=True, max_length=150, null=True)),
                ('type_of_indicator', models.TextField(blank=True, max_length=150, null=True)),
                ('m_code', models.ForeignKey(db_column='m_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Modules')),
            ],
            options={
                'db_table': 'modules_indicator_mst',
            },
        ),
        migrations.CreateModel(
            name='demo_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('city', models.TextField(blank=True, max_length=100, null=True)),
                ('demo_1', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_2', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_3', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_4', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_5', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_6', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_7', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_8', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_9', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_10', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_11', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_12', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_13', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_14', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_15', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_16', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_17', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_18', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_19', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_20', models.TextField(blank=True, max_length=150, null=True)),
                ('user', models.TextField(blank=True, max_length=150, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'demo_data',
                'unique_together': {('year', 'city')},
            },
        ),
    ]
