# Generated by Django 2.2.10 on 2021-07-01 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_authgroup_authgrouppermissions_authpermission_authusergroups_authuseruserpermissions_city_mst_demo_d'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City_mst',
        ),
        migrations.DeleteModel(
            name='demo_data',
        ),
        migrations.RemoveField(
            model_name='modules_indicator',
            name='m_code',
        ),
        migrations.DeleteModel(
            name='UserWithcity',
        ),
        migrations.DeleteModel(
            name='Modules',
        ),
        migrations.DeleteModel(
            name='Modules_indicator',
        ),
    ]
