# Generated by Django 2.2.10 on 2021-07-01 12:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210701_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='City_mst',
            fields=[
                ('city_code', models.TextField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('city_name', models.TextField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'city_mst',
            },
        ),
        migrations.CreateModel(
            name='Modules',
            fields=[
                ('m_code', models.TextField(blank=True, max_length=10, primary_key=True, serialize=False)),
                ('m_desc', models.TextField(blank=True, max_length=150, null=True)),
                ('s_no', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'modules_mst',
            },
        ),
        migrations.CreateModel(
            name='UserWithcity',
            fields=[
                ('s_no', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.TextField(blank=True, max_length=10)),
                ('city_name', models.TextField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'userwithcity',
                'unique_together': {('user_id', 'city_name')},
            },
        ),
        migrations.CreateModel(
            name='Modules_indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.FloatField(blank=True, null=True)),
                ('sub_theme', models.TextField(blank=True, max_length=150, null=True)),
                ('indicator', models.TextField(blank=True, max_length=150, null=True)),
                ('formula', models.TextField(blank=True, max_length=150, null=True)),
                ('unit', models.TextField(blank=True, max_length=150, null=True)),
                ('benchmark', models.TextField(blank=True, max_length=150, null=True)),
                ('source_of_benchmark', models.TextField(blank=True, max_length=150, null=True)),
                ('category', models.TextField(blank=True, max_length=150, null=True)),
                ('type_of_indicator', models.TextField(blank=True, max_length=150, null=True)),
                ('m_code', models.ForeignKey(db_column='m_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Modules')),
            ],
            options={
                'db_table': 'modules_indicator_mst',
            },
        ),
        migrations.CreateModel(
            name='demo_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(blank=True, null=True)),
                ('city', models.TextField(blank=True, max_length=100, null=True)),
                ('demo_1', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_2', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_3', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_4', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_5', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_6', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_7', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_8', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_9', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_10', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_11', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_12', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_13', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_14', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_15', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_16', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_17', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_18', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_19', models.TextField(blank=True, max_length=150, null=True)),
                ('demo_20', models.TextField(blank=True, max_length=150, null=True)),
                ('user', models.TextField(blank=True, max_length=150, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'demo_data',
                'unique_together': {('year', 'city')},
            },
        ),
    ]
