# Generated by Django 2.2.10 on 2021-07-03 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_city_mst_demo_data_modules_modules_indicator_userwithcity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point_Indicator',
            fields=[
                ('p_id', models.AutoField(primary_key=True, serialize=False)),
                ('indicator', models.TextField(blank=True, max_length=150, null=True)),
                ('point_desc', models.TextField(blank=True, max_length=150, null=True)),
                ('input_type', models.TextField(blank=True, max_length=150, null=True)),
                ('m_code', models.ForeignKey(db_column='m_code', null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Modules')),
            ],
            options={
                'db_table': 'point_indicator_mst',
            },
        ),
        migrations.CreateModel(
            name='DataPoint_Indicator',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('p_id', models.TextField(blank=True, max_length=5, null=True)),
                ('m_code', models.TextField(blank=True, max_length=150, null=True)),
                ('indicator', models.TextField(blank=True, max_length=150, null=True)),
                ('point_desc', models.TextField(blank=True, max_length=150, null=True)),
                ('point_value', models.TextField(blank=True, max_length=150, null=True)),
                ('point_remark', models.TextField(blank=True, max_length=150, null=True)),
                ('point_attach', models.FileField(blank=True, null=True, upload_to='module1')),
                ('input_type', models.TextField(blank=True, max_length=150, null=True)),
                ('city', models.TextField(blank=True, max_length=50, null=True)),
                ('year', models.TextField(blank=True, max_length=4, null=True)),
                ('user', models.TextField(blank=True, max_length=150, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'datapoint_indicator_mst',
                'unique_together': {('p_id', 'city', 'year', 'm_code')},
            },
        ),
    ]
